name: bstage2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  dio: ^4.0.6
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.13
  flutter_facebook_auth: ^4.2.0
  go_router: ^3.0.7
  flare_flutter: ^3.0.2
  flutter_svg: ^1.0.3
  simple_animations: ^4.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0
  faker: ^2.0.0
  bloc_test: ^9.0.3
  network_image_mock: ^2.1.0


flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/animations/
    - lib/ui/assets/icon/
    - lib/ui/assets/icon/otherIcons/
    - lib/ui/assets/icon/pngs/
    - lib/ui/assets/icon/splash/
    - lib/ui/assets/icon/svgs/
    - lib/ui/assets/images/backgrounds/
    - lib/ui/assets/images/categories/

  fonts:
    - family: Lato-Regular
      fonts:
        - asset: lib/ui/assets/fonts/Lato-Regular.ttf

    - family: Lato-Bold
      fonts:
        - asset: lib/ui/assets/fonts/Lato-Bold.ttf

    - family: Lato-Light
      fonts:
        - asset: lib/ui/assets/fonts/Lato-Light.ttf

    - family: BstageIcons
      fonts:
        - asset: lib/ui/assets/fonts/BstageIcons.ttf

